### ISSUE TITLE
S3 Mapping: Object

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/DataProxy#18]
Objects in S3 can not be simply mapped to AOS objects since updating is handled differently. In AOS an update always creates a new object with a new unique ID, while in S3 the objects ID (the key) would remain the same and only a new revision (version) is created.
A mapping could look like this:

- Each new object has a unique key as a separate field equivalent to the key in S3 to identify and object across all of its revisions that can be set by the user.
- In the S3 API only this key will be referenced, although internally the id is used.
This would probably require changes in the database and API.

**Comment by St4NNi** [comment]
Closed because it is irrelevant -> V1
