### ISSUE TITLE
S3 upload fails occasionally with "SignatureDoesNotMatch"

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/DataProxy#53]
I've uploaded a directory with 533 files via S3 (with s5cmd) and it gave the following error message a few times during upload:

```
ERROR "cp 160-1_OFOS-11_subset/SO268-2_160-1_OFOS_SO_CAM-1_20190427_170842.JPG s3://biigletest/biiglecollection/160-1_OFOS-11_subset/SO268-2_160-1_OFOS_SO_CAM-1_20190427_170842.JPG": SignatureDoesNotMatch:  status code: 403, request id: , host id:
```

When I view the dataset in the web UI, it only has 520 files, so some were not uploaded (because of the error?).

**Comment by mzur** [comment]
Also it seems that some files were created as objects but have zero size.

**Comment by das-Abroxas** [comment]
Unfortunately, we could not reproduce the problem, neither in a local setup nor in the Aruna testing instance. If you give us a little more information about the setup and parameters used etc., we can hopefully narrow it down a little better.

In any case, there is also the possibility that the error is somehow related to the _s5cmd_ client. For example, _s5cmd_ has the interesting default of starting up to 256 worker threads simultaneously. This means that in most of the cases there is not much bandwidth left for the individual upload, the upload of each individual thread takes much longer and is therefore susceptible to more error sources. In general, I would recommend adjusting the `--numworkers` parameter a little downwards when uploading via s5cmd, depending on the size of the individual files.

Regarding the files that were created as objects but whose upload appears to have been interrupted, the upload can simply be repeated. The objects are then still in the staging phase with the status `Initializing`, which means that the object is waiting for the upload of data. As soon as the upload is successfully completed, the object is also completed.

**Comment by mzur** [comment]
If you could not reproduce this then it's fine. Feel free to close this issue. I'll let you know when I observe this again.
